pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Restore Dependencies') {
            steps {
                sh 'dotnet restore ApiChallenge/ApiChallenge.csproj'
            }
        }
        stage('Build') {
            steps {
                sh 'dotnet build ApiChallenge/ApiChallenge.csproj -c Release'
            }
        }
        stage('Publish') {
            steps {
                sh 'dotnet publish ApiChallenge/ApiChallenge.csproj -c Release -o ./publish'
            }
        }
        stage('Dockerize') {
            steps {
                dir('ApiChallenge') { // Naviguer vers le dossier ApiChallenge
                    sh 'docker build -t douaema/api-challenge:latest -f Dockerfile .'
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push douaema/api-challenge:latest'
                }
            }
        }
    }
}
