pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Restore Dependencies') {
            steps {
                sh 'dotnet restore ApiChallenge/ApiChallenge.csproj'
            }
        }
        stage('Build') {
            steps {
                sh 'dotnet build ApiChallenge/ApiChallenge.csproj -c Release'
            }
        }
        stage('Test') {
            steps {
                sh 'dotnet test ApiChallenge/ApiChallenge.csproj'
            }
        }
        stage('Publish') {
            steps {
                sh 'dotnet publish ApiChallenge/ApiChallenge.csproj -c Release -o ./publish'
            }
        }
        stage('Dockerize') {
            steps {
                sh 'docker build -t douaema/api-challenge:latest .'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([ credentialsId: 'docker-hub-credentials', url: '' ]) {
                    sh 'docker push douaema/api-challenge:latest'
                }
            }
        }
    }
}
